import Foundation
import SPPCore

// MARK: - Shared Utilities

private extension SPPColor {
    /// Renders as a SwiftUI Color initialiser literal.
    var swiftUILiteral: String {
        "Color(red: \(red), green: \(green), blue: \(blue), opacity: \(alpha))"
    }

    /// Renders as a UIColor initialiser literal.
    var uiColorLiteral: String {
        "UIColor(red: \(red), green: \(green), blue: \(blue), alpha: \(alpha))"
    }
}

private extension SPPEdgeInsets {
    var isZero: Bool { top == 0 && leading == 0 && bottom == 0 && trailing == 0 }
}

private extension ComponentStyle {
    var isDefault: Bool {
        backgroundColor == nil && foregroundColor == nil && cornerRadius == 0 &&
        borderWidth == 0 && opacity == 1.0 && shadowRadius == 0 && padding.isZero
    }
}

// MARK: - SwiftUICodeGenerator

/// Generates a SwiftUI `View` file from a `BuilderDocument`.
public struct SwiftUICodeGenerator: Sendable {
    public init() {}

    public func generate(from document: BuilderDocument) -> String {
        let typeName = swiftTypeName(document.name) + "View"
        var lines: [String] = []
        lines += [
            "import SwiftUI",
            "",
            "// Generated by SPPUIBuilderKit — do not edit manually.",
            "",
            "struct \(typeName): View {",
            "    var body: some View {"
        ]

        if document.rootComponents.isEmpty {
            lines += [
                "        EmptyView()",
            ]
        } else if document.rootComponents.count == 1 {
            lines += componentLines(document.rootComponents[0], indent: 2)
        } else {
            lines.append("        ZStack {")
            for component in document.rootComponents {
                lines += componentLines(component, indent: 3)
            }
            lines.append("        }")
        }

        lines += [
            "    }",
            "}",
            "",
            "#if DEBUG",
            "struct \(typeName)_Previews: PreviewProvider {",
            "    static var previews: some View {",
            "        \(typeName)()",
            "    }",
            "}",
            "#endif",
        ]

        return lines.joined(separator: "\n")
    }

    // MARK: Per-component code

    private func componentLines(_ component: SPPUIComponent, indent: Int) -> [String] {
        let pad = String(repeating: "    ", count: indent)
        var lines: [String] = []

        // Build the primary view expression
        let viewExpr = primaryExpression(for: component)

        // Collect modifiers
        var modifiers: [String] = []

        // Frame
        let w = component.frame.size.width
        let h = component.frame.size.height
        if w > 0 || h > 0 {
            modifiers.append(".frame(width: \(w), height: \(h))")
        }

        // Padding
        let p = component.style.padding
        if !p.isZero {
            modifiers.append(
                ".padding(EdgeInsets(top: \(p.top), leading: \(p.leading), bottom: \(p.bottom), trailing: \(p.trailing)))"
            )
        }

        // Background
        if let bg = component.style.backgroundColor {
            modifiers.append(".background(\(bg.swiftUILiteral))")
        }

        // Foreground
        if let fg = component.style.foregroundColor {
            modifiers.append(".foregroundColor(\(fg.swiftUILiteral))")
        }

        // Corner radius
        if component.style.cornerRadius > 0 {
            modifiers.append(".cornerRadius(\(component.style.cornerRadius))")
        }

        // Border
        if component.style.borderWidth > 0, let bc = component.style.borderColor {
            modifiers.append(".border(\(bc.swiftUILiteral), width: \(component.style.borderWidth))")
        }

        // Opacity
        if component.style.opacity != 1.0 {
            modifiers.append(".opacity(\(component.style.opacity))")
        }

        // Shadow
        if component.style.shadowRadius > 0 {
            let sc = component.style.shadowColor.map { $0.swiftUILiteral } ?? "Color.black.opacity(0.3)"
            let ox = component.style.shadowOffset.x
            let oy = component.style.shadowOffset.y
            modifiers.append(".shadow(color: \(sc), radius: \(component.style.shadowRadius), x: \(ox), y: \(oy))")
        }

        // Hidden
        if component.behavior.isHidden {
            modifiers.append(".hidden()")
        }

        // Accessibility
        if let label = component.behavior.accessibilityLabel {
            modifiers.append(".accessibilityLabel(\"\(label)\")")
        }
        if let ident = component.behavior.accessibilityIdentifier {
            modifiers.append(".accessibilityIdentifier(\"\(ident)\")")
        }

        if modifiers.isEmpty {
            lines.append("\(pad)\(viewExpr)")
        } else {
            lines.append("\(pad)\(viewExpr)")
            for mod in modifiers {
                lines.append("\(pad)    \(mod)")
            }
        }

        return lines
    }

    private func primaryExpression(for component: SPPUIComponent) -> String {
        switch component.kind {
        case .label:
            let text = component.properties["text"] ?? component.name
            if let font = component.style.font {
                return "Text(\"\(escaped(text))\")\n            .font(.custom(\"\(font.family)\", size: \(font.size)))"
            }
            return "Text(\"\(escaped(text))\")"

        case .button:
            let title = component.properties["text"] ?? component.name
            let actionID = component.behavior.onTapActionID ?? ""
            if actionID.isEmpty {
                return "Button(\"\(escaped(title))\") { }"
            }
            return "Button(\"\(escaped(title))\") { /* action: \(actionID) */ }"

        case .textField:
            let placeholder = component.properties["placeholder"] ?? component.name
            return "TextField(\"\(escaped(placeholder))\", text: .constant(\"\"))"

        case .imageView:
            let imageName = component.properties["imageName"] ?? "photo"
            if imageName.hasPrefix("system:") {
                let systemName = String(imageName.dropFirst("system:".count))
                return "Image(systemName: \"\(systemName)\")"
            }
            return "Image(\"\(imageName)\")"

        case .stackView:
            let axis = component.properties["axis"].flatMap { StackAxis(rawValue: $0) } ?? .vertical
            let spacing = Double(component.properties["spacing"] ?? "8") ?? 8
            let content = childrenContent(component.children, indent: 2)
            if axis == .horizontal {
                return "HStack(spacing: \(spacing)) {\n\(content)\n        }"
            } else {
                return "VStack(spacing: \(spacing)) {\n\(content)\n        }"
            }

        case .scrollView:
            let content = childrenContent(component.children, indent: 2)
            return "ScrollView {\n\(content)\n        }"

        case .switch_:
            return "Toggle(\"\", isOn: .constant(false))\n            .labelsHidden()"

        case .slider:
            let min = component.properties["min"] ?? "0"
            let max = component.properties["max"] ?? "100"
            return "Slider(value: .constant(0.5), in: \(min)...\(max))"

        case .progressView:
            let progress = Double(component.properties["progress"] ?? "0.5") ?? 0.5
            return "ProgressView(value: \(progress))"

        case .activityIndicator:
            return "ProgressView()"

        case .tableView, .collectionView:
            let content = childrenContent(component.children, indent: 2)
            return "ScrollView {\n\(content)\n        }"

        case .view:
            if component.children.isEmpty {
                return "Rectangle().fill(Color.clear)"
            }
            let content = childrenContent(component.children, indent: 2)
            return "ZStack {\n\(content)\n        }"

        case .custom:
            let typeName = component.properties["typeName"] ?? "AnyView"
            return "// Custom: \(typeName)\n        EmptyView()"
        }
    }

    private func childrenContent(_ children: [SPPUIComponent], indent: Int) -> String {
        children.flatMap { componentLines($0, indent: indent + 1) }
            .joined(separator: "\n")
    }
}

// MARK: - UIKitCodeGenerator

/// Generates a UIKit `UIViewController` subclass from a `BuilderDocument`.
public struct UIKitCodeGenerator: Sendable {
    public init() {}

    public func generate(from document: BuilderDocument) -> String {
        let typeName = swiftTypeName(document.name) + "ViewController"
        var lines: [String] = []
        lines += [
            "import UIKit",
            "",
            "// Generated by SPPUIBuilderKit — do not edit manually.",
            "",
            "final class \(typeName): UIViewController {",
            "",
            "    override func viewDidLoad() {",
            "        super.viewDidLoad()",
        ]

        if let bg = document.rootComponents.first?.style.backgroundColor {
            lines.append("        view.backgroundColor = \(bg.uiColorLiteral)")
        } else {
            lines.append("        view.backgroundColor = .systemBackground")
        }
        lines.append("")

        for (i, component) in document.rootComponents.enumerated() {
            lines += componentSetupLines(component, varPrefix: "component\(i)", parentVar: "view", indent: 2)
        }

        lines += [
            "    }",
            "}",
        ]

        return lines.joined(separator: "\n")
    }

    // MARK: Per-component setup

    private func componentSetupLines(
        _ component: SPPUIComponent,
        varPrefix: String,
        parentVar: String,
        indent: Int
    ) -> [String] {
        let pad = String(repeating: "    ", count: indent)
        var lines: [String] = []
        let varName = varPrefix

        // Create view
        let createExpr = uiKitCreateExpression(for: component)
        lines.append("\(pad)let \(varName) = \(createExpr)")

        // Frame
        let f = component.frame
        lines.append(
            "\(pad)\(varName).frame = CGRect(x: \(f.minX), y: \(f.minY), width: \(f.size.width), height: \(f.size.height))"
        )

        // Background color
        if let bg = component.style.backgroundColor {
            lines.append("\(pad)\(varName).backgroundColor = \(bg.uiColorLiteral)")
        }

        // Corner radius
        if component.style.cornerRadius > 0 {
            lines.append("\(pad)\(varName).layer.cornerRadius = \(component.style.cornerRadius)")
            lines.append("\(pad)\(varName).layer.masksToBounds = true")
        }

        // Border
        if component.style.borderWidth > 0 {
            lines.append("\(pad)\(varName).layer.borderWidth = \(component.style.borderWidth)")
            if let bc = component.style.borderColor {
                lines.append("\(pad)\(varName).layer.borderColor = \(bc.uiColorLiteral).cgColor")
            }
        }

        // Shadow (doesn't mix with masksToBounds, but generate for completeness)
        if component.style.shadowRadius > 0 {
            lines.append("\(pad)\(varName).layer.shadowRadius = \(component.style.shadowRadius)")
            lines.append("\(pad)\(varName).layer.shadowOpacity = Float(\(component.style.shadowColor?.alpha ?? 0.3))")
            let sc = component.style.shadowColor ?? SPPColor(red: 0, green: 0, blue: 0, alpha: 0.3)
            lines.append("\(pad)\(varName).layer.shadowColor = \(sc.uiColorLiteral).cgColor")
            lines.append(
                "\(pad)\(varName).layer.shadowOffset = CGSize(width: \(component.style.shadowOffset.x), height: \(component.style.shadowOffset.y))"
            )
        }

        // Opacity
        if component.style.opacity != 1.0 {
            lines.append("\(pad)\(varName).alpha = \(component.style.opacity)")
        }

        // Hidden
        if component.behavior.isHidden {
            lines.append("\(pad)\(varName).isHidden = true")
        }

        // User interaction
        if !component.behavior.isUserInteractionEnabled {
            lines.append("\(pad)\(varName).isUserInteractionEnabled = false")
        }

        // Accessibility
        if let label = component.behavior.accessibilityLabel {
            lines.append("\(pad)\(varName).accessibilityLabel = \"\(escaped(label))\"")
        }
        if let ident = component.behavior.accessibilityIdentifier {
            lines.append("\(pad)\(varName).accessibilityIdentifier = \"\(escaped(ident))\"")
        }

        // Kind-specific configuration
        lines += uiKitKindConfig(component, varName: varName, indent: indent)

        // Add to parent
        lines.append("\(pad)\(parentVar).addSubview(\(varName))")
        lines.append("")

        // Recurse into children
        for (i, child) in component.children.enumerated() {
            lines += componentSetupLines(child, varPrefix: "\(varPrefix)_child\(i)", parentVar: varName, indent: indent)
        }

        return lines
    }

    private func uiKitCreateExpression(for component: SPPUIComponent) -> String {
        switch component.kind {
        case .label:           return "UILabel()"
        case .button:          return "UIButton(type: .system)"
        case .textField:       return "UITextField()"
        case .imageView:       return "UIImageView()"
        case .stackView:
            let axis = component.properties["axis"].flatMap { StackAxis(rawValue: $0) } ?? .vertical
            return axis == .horizontal
                ? "{ let sv = UIStackView(); sv.axis = .horizontal; return sv }()"
                : "{ let sv = UIStackView(); sv.axis = .vertical; return sv }()"
        case .scrollView:      return "UIScrollView()"
        case .tableView:       return "UITableView(frame: .zero, style: .plain)"
        case .collectionView:
            return "UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewFlowLayout())"
        case .switch_:         return "UISwitch()"
        case .slider:          return "UISlider()"
        case .progressView:    return "UIProgressView(progressViewStyle: .default)"
        case .activityIndicator: return "UIActivityIndicatorView(style: .medium)"
        case .view, .custom:   return "UIView()"
        }
    }

    private func uiKitKindConfig(_ component: SPPUIComponent, varName: String, indent: Int) -> [String] {
        let pad = String(repeating: "    ", count: indent)
        var lines: [String] = []
        switch component.kind {
        case .label:
            let text = component.properties["text"] ?? component.name
            lines.append("\(pad)\(varName).text = \"\(escaped(text))\"")
            if let fg = component.style.foregroundColor {
                lines.append("\(pad)\(varName).textColor = \(fg.uiColorLiteral)")
            }
            if let font = component.style.font {
                lines.append("\(pad)\(varName).font = UIFont(name: \"\(font.family)\", size: \(font.size)) ?? UIFont.systemFont(ofSize: \(font.size))")
            }
        case .button:
            let title = component.properties["text"] ?? component.name
            lines.append("\(pad)\(varName).setTitle(\"\(escaped(title))\", for: .normal)")
            if let fg = component.style.foregroundColor {
                lines.append("\(pad)\(varName).setTitleColor(\(fg.uiColorLiteral), for: .normal)")
            }
            if let tint = component.style.tintColor {
                lines.append("\(pad)\(varName).tintColor = \(tint.uiColorLiteral)")
            }
        case .textField:
            let placeholder = component.properties["placeholder"] ?? ""
            lines.append("\(pad)\(varName).placeholder = \"\(escaped(placeholder))\"")
        case .imageView:
            let imageName = component.properties["imageName"] ?? ""
            if !imageName.isEmpty {
                if imageName.hasPrefix("system:") {
                    let sysName = String(imageName.dropFirst("system:".count))
                    lines.append("\(pad)\(varName).image = UIImage(systemName: \"\(sysName)\")")
                } else {
                    lines.append("\(pad)\(varName).image = UIImage(named: \"\(imageName)\")")
                }
            }
            let modeRaw = component.properties["contentMode"] ?? ContentMode.scaleAspectFit.rawValue
            let uiMode = contentModeUIKit(modeRaw)
            lines.append("\(pad)\(varName).contentMode = \(uiMode)")
        case .stackView:
            let spacing = Double(component.properties["spacing"] ?? "8") ?? 8
            lines.append("\(pad)\(varName).spacing = \(spacing)")
            lines.append("\(pad)\(varName).distribution = .fill")
            lines.append("\(pad)\(varName).alignment = .fill")
        case .slider:
            let min = Float(component.properties["min"] ?? "0") ?? 0
            let max = Float(component.properties["max"] ?? "100") ?? 100
            lines.append("\(pad)\(varName).minimumValue = \(min)")
            lines.append("\(pad)\(varName).maximumValue = \(max)")
        case .progressView:
            let progress = Float(component.properties["progress"] ?? "0.5") ?? 0.5
            lines.append("\(pad)\(varName).progress = \(progress)")
        case .activityIndicator:
            lines.append("\(pad)\(varName).startAnimating()")
        default:
            break
        }
        return lines
    }

    private func contentModeUIKit(_ raw: String) -> String {
        switch ContentMode(rawValue: raw) {
        case .scaleToFill:   return ".scaleToFill"
        case .scaleAspectFit:  return ".scaleAspectFit"
        case .scaleAspectFill: return ".scaleAspectFill"
        case .center:        return ".center"
        case .none:          return ".scaleAspectFit"
        }
    }
}

// MARK: - LogosBootstrapGenerator

/// Generates a Logos %ctor / %hook snippet that installs the component hierarchy
/// inside an existing Objective-C class.
public struct LogosBootstrapGenerator: Sendable {
    public init() {}

    public func generate(from document: BuilderDocument, targetClassName: String) -> String {
        let hookName = swiftTypeName(document.name) + "Hook"
        var lines: [String] = []
        lines += [
            "// Generated by SPPUIBuilderKit — do not edit manually.",
            "// Target: \(targetClassName)",
            "",
            "#import <UIKit/UIKit.h>",
            "",
            "%hook \(targetClassName)",
            "",
            "- (void)viewDidLoad {",
            "    %orig;",
            "    [self \(camelCase("install_" + document.name) + "Views")];",
            "}",
            "",
            "%%new",
            "- (void)install\(swiftTypeName(document.name))Views {",
            "    UIView *rootView = self.view;",
        ]

        for (i, component) in document.rootComponents.enumerated() {
            lines += logosSetupLines(component, varPrefix: "v\(i)", parentVar: "rootView", indent: 1)
        }

        lines += [
            "}",
            "",
            "%end",
            "",
            "%ctor {",
            "    // Ensure the class exists at runtime before hooking.",
            "    if (objc_getClass(\"\(targetClassName)\")) {",
            "        %init(\(hookName));",
            "    }",
            "}",
        ]

        return lines.joined(separator: "\n")
    }

    private func logosSetupLines(
        _ component: SPPUIComponent,
        varPrefix: String,
        parentVar: String,
        indent: Int
    ) -> [String] {
        let pad = String(repeating: "    ", count: indent)
        var lines: [String] = []
        let varName = varPrefix

        // Create
        let createExpr = logosCreateExpr(for: component)
        lines.append("\(pad)UIView *\(varName) = \(createExpr);")

        // Frame
        let f = component.frame
        lines.append(
            "\(pad)\(varName).frame = CGRectMake(\(f.minX), \(f.minY), \(f.size.width), \(f.size.height));"
        )

        // Background
        if let bg = component.style.backgroundColor {
            lines.append("\(pad)\(varName).backgroundColor = \(objcColor(bg));")
        }

        // Corner radius
        if component.style.cornerRadius > 0 {
            lines.append("\(pad)\(varName).layer.cornerRadius = \(component.style.cornerRadius);")
            lines.append("\(pad)\(varName).layer.masksToBounds = YES;")
        }

        // Alpha
        if component.style.opacity != 1.0 {
            lines.append("\(pad)\(varName).alpha = \(component.style.opacity);")
        }

        // Hidden
        if component.behavior.isHidden {
            lines.append("\(pad)\(varName).hidden = YES;")
        }

        // Kind-specific
        lines += logosKindConfig(component, varName: varName, indent: indent)

        // Add to parent
        lines.append("\(pad)[\(parentVar) addSubview:\(varName)];")
        lines.append("")

        // Recurse
        for (i, child) in component.children.enumerated() {
            lines += logosSetupLines(child, varPrefix: "\(varPrefix)c\(i)", parentVar: varName, indent: indent)
        }

        return lines
    }

    private func logosCreateExpr(for component: SPPUIComponent) -> String {
        switch component.kind {
        case .label:           return "[[UILabel alloc] init]"
        case .button:          return "[UIButton buttonWithType:UIButtonTypeSystem]"
        case .textField:       return "[[UITextField alloc] init]"
        case .imageView:       return "[[UIImageView alloc] init]"
        case .stackView:       return "[[UIStackView alloc] init]"
        case .scrollView:      return "[[UIScrollView alloc] init]"
        case .tableView:       return "[[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain]"
        case .collectionView:
            return "[[UICollectionView alloc] initWithFrame:CGRectZero collectionViewLayout:[[UICollectionViewFlowLayout alloc] init]]"
        case .switch_:         return "[[UISwitch alloc] init]"
        case .slider:          return "[[UISlider alloc] init]"
        case .progressView:    return "[[UIProgressView alloc] initWithProgressViewStyle:UIProgressViewStyleDefault]"
        case .activityIndicator: return "[[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium]"
        case .view, .custom:   return "[[UIView alloc] init]"
        }
    }

    private func logosKindConfig(_ component: SPPUIComponent, varName: String, indent: Int) -> [String] {
        let pad = String(repeating: "    ", count: indent)
        var lines: [String] = []
        switch component.kind {
        case .label:
            let text = component.properties["text"] ?? component.name
            lines.append("\(pad)((UILabel *)\(varName)).text = @\"\(escaped(text))\";")
            if let fg = component.style.foregroundColor {
                lines.append("\(pad)((UILabel *)\(varName)).textColor = \(objcColor(fg));")
            }
        case .button:
            let title = component.properties["text"] ?? component.name
            lines.append("\(pad)[((UIButton *)\(varName)) setTitle:@\"\(escaped(title))\" forState:UIControlStateNormal];")
        case .textField:
            let placeholder = component.properties["placeholder"] ?? ""
            lines.append("\(pad)((UITextField *)\(varName)).placeholder = @\"\(escaped(placeholder))\";")
        case .imageView:
            let imageName = component.properties["imageName"] ?? ""
            if !imageName.isEmpty {
                if imageName.hasPrefix("system:") {
                    let sysName = String(imageName.dropFirst("system:".count))
                    lines.append("\(pad)((UIImageView *)\(varName)).image = [UIImage systemImageNamed:@\"\(sysName)\"];")
                } else {
                    lines.append("\(pad)((UIImageView *)\(varName)).image = [UIImage imageNamed:@\"\(imageName)\"];")
                }
            }
        case .activityIndicator:
            lines.append("\(pad)[((UIActivityIndicatorView *)\(varName)) startAnimating];")
        default:
            break
        }
        return lines
    }

    private func objcColor(_ color: SPPColor) -> String {
        "[UIColor colorWithRed:\(color.red) green:\(color.green) blue:\(color.blue) alpha:\(color.alpha)]"
    }
}

// MARK: - OrionOverlayAdapter

/// Generates an Orion Swift overlay that installs views inside a hooked class.
public struct OrionOverlayAdapter: Sendable {
    public init() {}

    public func generate(from document: BuilderDocument, targetClassName: String) -> String {
        let tweakName = swiftTypeName(document.name) + "Tweak"
        let hookName = tweakName + "Class"
        var lines: [String] = []
        lines += [
            "import Orion",
            "import UIKit",
            "",
            "// Generated by SPPUIBuilderKit — do not edit manually.",
            "// Target: \(targetClassName)",
            "",
            "struct \(tweakName): Tweak {}",
            "",
            "class \(hookName): ClassHook<NSObject> {",
            "    typealias Target = AnyObject",
            "    static let targetName = \"\(targetClassName)\"",
            "",
            "    func viewDidLoad() {",
            "        orig.viewDidLoad()",
            "        guard let vc = self.target as? UIViewController else { return }",
            "        let rootView = vc.view!",
        ]

        for (i, component) in document.rootComponents.enumerated() {
            lines += orionSetupLines(component, varPrefix: "v\(i)", parentVar: "rootView", indent: 2)
        }

        lines += [
            "    }",
            "}",
        ]

        return lines.joined(separator: "\n")
    }

    private func orionSetupLines(
        _ component: SPPUIComponent,
        varPrefix: String,
        parentVar: String,
        indent: Int
    ) -> [String] {
        let pad = String(repeating: "    ", count: indent)
        var lines: [String] = []
        let varName = varPrefix

        // Create
        let createExpr = orionCreateExpr(for: component)
        lines.append("\(pad)let \(varName) = \(createExpr)")

        // Frame
        let f = component.frame
        lines.append(
            "\(pad)\(varName).frame = CGRect(x: \(f.minX), y: \(f.minY), width: \(f.size.width), height: \(f.size.height))"
        )

        // Background
        if let bg = component.style.backgroundColor {
            lines.append("\(pad)\(varName).backgroundColor = \(bg.uiColorLiteral)")
        }

        // Corner radius
        if component.style.cornerRadius > 0 {
            lines.append("\(pad)\(varName).layer.cornerRadius = \(component.style.cornerRadius)")
            lines.append("\(pad)\(varName).layer.masksToBounds = true")
        }

        // Opacity
        if component.style.opacity != 1.0 {
            lines.append("\(pad)\(varName).alpha = \(component.style.opacity)")
        }

        // Hidden
        if component.behavior.isHidden {
            lines.append("\(pad)\(varName).isHidden = true")
        }

        // Accessibility
        if let label = component.behavior.accessibilityLabel {
            lines.append("\(pad)\(varName).accessibilityLabel = \"\(escaped(label))\"")
        }
        if let ident = component.behavior.accessibilityIdentifier {
            lines.append("\(pad)\(varName).accessibilityIdentifier = \"\(escaped(ident))\"")
        }

        // Kind-specific
        lines += orionKindConfig(component, varName: varName, indent: indent)

        // Add to parent
        lines.append("\(pad)\(parentVar).addSubview(\(varName))")
        lines.append("")

        // Recurse
        for (i, child) in component.children.enumerated() {
            lines += orionSetupLines(child, varPrefix: "\(varPrefix)c\(i)", parentVar: varName, indent: indent)
        }

        return lines
    }

    private func orionCreateExpr(for component: SPPUIComponent) -> String {
        switch component.kind {
        case .label:           return "UILabel()"
        case .button:          return "UIButton(type: .system)"
        case .textField:       return "UITextField()"
        case .imageView:       return "UIImageView()"
        case .stackView:
            let axis = component.properties["axis"].flatMap { StackAxis(rawValue: $0) } ?? .vertical
            return axis == .horizontal
                ? "{ let sv = UIStackView(); sv.axis = .horizontal; return sv }()"
                : "{ let sv = UIStackView(); sv.axis = .vertical; return sv }()"
        case .scrollView:      return "UIScrollView()"
        case .tableView:       return "UITableView(frame: .zero, style: .plain)"
        case .collectionView:
            return "UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewFlowLayout())"
        case .switch_:         return "UISwitch()"
        case .slider:          return "UISlider()"
        case .progressView:    return "UIProgressView(progressViewStyle: .default)"
        case .activityIndicator: return "UIActivityIndicatorView(style: .medium)"
        case .view, .custom:   return "UIView()"
        }
    }

    private func orionKindConfig(_ component: SPPUIComponent, varName: String, indent: Int) -> [String] {
        let pad = String(repeating: "    ", count: indent)
        var lines: [String] = []
        switch component.kind {
        case .label:
            let text = component.properties["text"] ?? component.name
            lines.append("\(pad)(\(varName) as! UILabel).text = \"\(escaped(text))\"")
            if let fg = component.style.foregroundColor {
                lines.append("\(pad)(\(varName) as! UILabel).textColor = \(fg.uiColorLiteral)")
            }
            if let font = component.style.font {
                lines.append("\(pad)(\(varName) as! UILabel).font = UIFont(name: \"\(font.family)\", size: \(font.size)) ?? .systemFont(ofSize: \(font.size))")
            }
        case .button:
            let title = component.properties["text"] ?? component.name
            lines.append("\(pad)(\(varName) as! UIButton).setTitle(\"\(escaped(title))\", for: .normal)")
            if let fg = component.style.foregroundColor {
                lines.append("\(pad)(\(varName) as! UIButton).setTitleColor(\(fg.uiColorLiteral), for: .normal)")
            }
        case .textField:
            let placeholder = component.properties["placeholder"] ?? ""
            lines.append("\(pad)(\(varName) as! UITextField).placeholder = \"\(escaped(placeholder))\"")
        case .imageView:
            let imageName = component.properties["imageName"] ?? ""
            if !imageName.isEmpty {
                if imageName.hasPrefix("system:") {
                    let sysName = String(imageName.dropFirst("system:".count))
                    lines.append("\(pad)(\(varName) as! UIImageView).image = UIImage(systemName: \"\(sysName)\")")
                } else {
                    lines.append("\(pad)(\(varName) as! UIImageView).image = UIImage(named: \"\(imageName)\")")
                }
            }
        case .stackView:
            let spacing = Double(component.properties["spacing"] ?? "8") ?? 8
            lines.append("\(pad)(\(varName) as! UIStackView).spacing = \(spacing)")
        case .slider:
            let min = Float(component.properties["min"] ?? "0") ?? 0
            let max = Float(component.properties["max"] ?? "100") ?? 100
            lines.append("\(pad)(\(varName) as! UISlider).minimumValue = \(min)")
            lines.append("\(pad)(\(varName) as! UISlider).maximumValue = \(max)")
        case .progressView:
            let progress = Float(component.properties["progress"] ?? "0.5") ?? 0.5
            lines.append("\(pad)(\(varName) as! UIProgressView).progress = \(progress)")
        case .activityIndicator:
            lines.append("\(pad)(\(varName) as! UIActivityIndicatorView).startAnimating()")
        default:
            break
        }
        return lines
    }
}

// MARK: - String helpers (file-private)

/// Turns an arbitrary name into a PascalCase Swift type identifier.
private func swiftTypeName(_ raw: String) -> String {
    let words = raw
        .components(separatedBy: CharacterSet.alphanumerics.inverted)
        .filter { !$0.isEmpty }
    return words.map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
}

/// Turns an arbitrary name into a camelCase Swift identifier.
private func camelCase(_ raw: String) -> String {
    let pascal = swiftTypeName(raw)
    guard !pascal.isEmpty else { return "" }
    return pascal.prefix(1).lowercased() + pascal.dropFirst()
}

/// Escapes characters that would break a Swift or ObjC string literal.
private func escaped(_ string: String) -> String {
    string
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
        .replacingOccurrences(of: "\n", with: "\\n")
        .replacingOccurrences(of: "\r", with: "\\r")
        .replacingOccurrences(of: "\t", with: "\\t")
}
